---   
spring:
  profiles: slave1     
server:
  port: 8761
eureka:
  instance:
    hostname: slave1
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/
---
spring:
  profiles: slave2   
server:
  port: 8762
eureka:
  instance:
    hostname: slave2
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/

 

