server:
  port: 8770

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunyitc/diagramdev.git
          searchPaths: SC_Master/SC_S_Config_Server_Git/src/main/resources/configfile
          # username: 
          # password: 
      label: master
  application:
    name: config-server

eureka:
  client:
    service-url:
      defaultZone : http://slave1:8761/eureka/
