server:
  port: 8769
  
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunyitc/diagramdev/tree/master/SC_Master/SC_S_Config_Server_Git/src/main
          searchPaths: resources
          username: 
          password: 
      label: master
  application:
    name: config-server


