eureka:
  client:
    service-url:
      defaultZone : http://slave1:8761/eureka/
     
server:
  port: 5000

spring:
  application:
    name: eureka-zuul


zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
    ribbonapi:
      path:  /ribbonapi/**
      serviceId: ribbon-consumer
    feignapi:
      path: /feignapi/**
      serviceId: feign-consumer
